//! Create Organization saga state machine and step definitions.

use std::time::Duration;

use chrono::{DateTime, Utc};
use inferadb_ledger_types::{OrganizationId, OrganizationSlug, Region, UserId};
use serde::{Deserialize, Serialize};

use super::{MAX_BACKOFF, MAX_RETRIES, OrganizationTier, SagaId};

/// State machine for the Create Organization saga.
///
/// Coordinates writes across GLOBAL + regional stores:
/// 1. GLOBAL: allocate OrganizationId/OrganizationSlug, create directory entry
/// 2. Regional: finalize OrganizationProfile + write ownership membership
/// 3. GLOBAL: update directory status to Active
///
/// Compensation in reverse: step 3 → revert directory status,
/// step 2 → delete profile + membership from regional store,
/// step 1 → delete directory entry + slug index from GLOBAL.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub enum CreateOrganizationSagaState {
    /// Initial state: about to allocate IDs and create directory entry in GLOBAL.
    Pending,
    /// Step 1 complete: directory entry created in GLOBAL with Provisioning status.
    DirectoryCreated {
        /// Allocated internal organization ID.
        organization_id: OrganizationId,
        /// Allocated external Snowflake slug.
        organization_slug: OrganizationSlug,
    },
    /// Step 2 complete: profile finalized and ownership membership written in regional store.
    ProfileWritten {
        /// The organization's internal ID.
        organization_id: OrganizationId,
        /// The organization's external slug.
        organization_slug: OrganizationSlug,
    },
    /// Step 3 complete: directory entry marked Active in GLOBAL.
    Completed {
        /// Created organization's internal ID.
        organization_id: OrganizationId,
        /// Created organization's external slug.
        organization_slug: OrganizationSlug,
    },
    /// Saga failed after exhausting retries.
    Failed {
        /// The step that failed (0-indexed).
        step: u8,
        /// Error description.
        error: String,
    },
    /// Saga failed and compensation completed.
    Compensated {
        /// The step that failed.
        step: u8,
        /// Summary of compensation actions taken.
        cleanup_summary: String,
    },
    /// Saga exceeded timeout and was auto-compensated.
    TimedOut,
}

/// Input parameters for Create Organization saga.
///
/// PII (organization name) is intentionally excluded — the saga is stored in
/// the global control plane, and only pseudonymous identifiers are permitted.
/// The organization name is passed in-memory via `OrgPii` through the
/// saga orchestrator handle, never persisted in the GLOBAL Raft log.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CreateOrganizationInput {
    /// Pre-generated external Snowflake slug for the organization.
    /// Generated by the service handler so it can be returned immediately
    /// in the fire-and-forget response.
    pub slug: OrganizationSlug,
    /// Data residency region for the organization.
    pub region: Region,
    /// Billing tier for the organization.
    pub tier: OrganizationTier,
    /// Initial administrator for this organization.
    pub admin: UserId,
}

/// Record for the Create Organization saga, tracking state and retry progress.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CreateOrganizationSaga {
    /// Unique saga identifier.
    pub id: SagaId,
    /// Current state.
    pub state: CreateOrganizationSagaState,
    /// Input parameters (PII-free).
    pub input: CreateOrganizationInput,
    /// When the saga was created.
    pub created_at: DateTime<Utc>,
    /// When the saga was last updated.
    pub updated_at: DateTime<Utc>,
    /// Number of retry attempts.
    pub retries: u8,
    /// Next retry time (for exponential backoff).
    pub next_retry_at: Option<DateTime<Utc>>,
}

impl CreateOrganizationSaga {
    /// Creates a new saga in Pending state.
    pub fn new(id: SagaId, input: CreateOrganizationInput) -> Self {
        let now = Utc::now();
        Self {
            id,
            state: CreateOrganizationSagaState::Pending,
            input,
            created_at: now,
            updated_at: now,
            retries: 0,
            next_retry_at: None,
        }
    }

    /// Checks if the saga is complete (success or permanently failed).
    pub fn is_terminal(&self) -> bool {
        matches!(
            self.state,
            CreateOrganizationSagaState::Completed { .. }
                | CreateOrganizationSagaState::Failed { .. }
                | CreateOrganizationSagaState::Compensated { .. }
                | CreateOrganizationSagaState::TimedOut
        )
    }

    /// Checks if the saga is ready for retry.
    pub fn is_ready_for_retry(&self) -> bool {
        if self.is_terminal() {
            return false;
        }
        match self.next_retry_at {
            Some(retry_at) => Utc::now() >= retry_at,
            None => true,
        }
    }

    /// Checks if the saga has exceeded the given timeout.
    pub fn is_timed_out(&self, timeout: Duration) -> bool {
        let elapsed = Utc::now() - self.created_at;
        elapsed > chrono::Duration::from_std(timeout).unwrap_or(chrono::Duration::MAX)
    }

    /// Calculates next backoff duration using exponential backoff.
    pub fn next_backoff(&self) -> Duration {
        let base = Duration::from_secs(1);
        let backoff = base * 2u32.saturating_pow(self.retries as u32);
        std::cmp::min(backoff, MAX_BACKOFF)
    }

    /// Transitions to a new state.
    pub fn transition(&mut self, new_state: CreateOrganizationSagaState) {
        self.state = new_state;
        self.updated_at = Utc::now();
        self.next_retry_at = None;
    }

    /// Marks as failed with error.
    ///
    /// After MAX_RETRIES failures, transitions to terminal Failed state.
    pub fn fail(&mut self, step: u8, error: String) {
        self.retries = self.retries.saturating_add(1);
        if self.retries >= MAX_RETRIES {
            self.state = CreateOrganizationSagaState::Failed { step, error };
        } else {
            let backoff = self.next_backoff();
            self.next_retry_at =
                Some(Utc::now() + chrono::Duration::from_std(backoff).unwrap_or_default());
        }
        self.updated_at = Utc::now();
    }

    /// Returns the step number for the current state.
    pub fn current_step(&self) -> u8 {
        match &self.state {
            CreateOrganizationSagaState::Pending => 0,
            CreateOrganizationSagaState::DirectoryCreated { .. } => 1,
            CreateOrganizationSagaState::ProfileWritten { .. } => 2,
            CreateOrganizationSagaState::Completed { .. }
            | CreateOrganizationSagaState::Failed { .. }
            | CreateOrganizationSagaState::Compensated { .. }
            | CreateOrganizationSagaState::TimedOut => 0,
        }
    }

    /// Returns the target region for the current step.
    ///
    /// Steps 0, 2 target GLOBAL; step 1 targets the organization's declared region.
    pub fn target_region(&self) -> Region {
        match &self.state {
            CreateOrganizationSagaState::Pending => Region::GLOBAL,
            CreateOrganizationSagaState::DirectoryCreated { .. } => self.input.region,
            CreateOrganizationSagaState::ProfileWritten { .. } => Region::GLOBAL,
            CreateOrganizationSagaState::Completed { .. }
            | CreateOrganizationSagaState::Failed { .. }
            | CreateOrganizationSagaState::Compensated { .. }
            | CreateOrganizationSagaState::TimedOut => Region::GLOBAL,
        }
    }
}
