//! Opcode allocation for the InferaDB Ledger wire protocol.
//!
//! Opcodes are 16-bit unsigned integers identifying RPCs on the wire. The
//! allocation is global across all services; cross-service collisions are
//! detected at compile time by the `define_protocol!` macro (Phase 0.0.D).
//!
//! # Reserved range (`0x0000`–`0x000F`)
//!
//! Reserved for protocol-level operations. Service RPCs MUST NOT use these
//! opcodes. The full per-service enumeration (the `OpCode` enum) is
//! generated by `define_protocol!` and lives in `crate::services`.
//!
//! # Service ranges
//!
//! Each service is allocated a contiguous 256-opcode range. The
//! `define_protocol!` macro asserts at compile time that every RPC in a
//! given service falls within its declared range.
//!
//! | Range | Service |
//! |---|---|
//! | `0x0000`–`0x000F` | Reserved (protocol-level) |
//! | `0x0010`–`0x00FF` | Read service |
//! | `0x0100`–`0x01FF` | Write service |
//! | `0x0200`–`0x02FF` | Organization service |
//! | `0x0300`–`0x03FF` | Vault service |
//! | `0x0400`–`0x04FF` | Schema service |
//! | `0x0500`–`0x05FF` | User service |
//! | `0x0600`–`0x06FF` | App service |
//! | `0x0700`–`0x07FF` | Invitation service |
//! | `0x0800`–`0x08FF` | Token service |
//! | `0x0900`–`0x09FF` | Events service |
//! | `0x0A00`–`0x0AFF` | Admin service |
//! | `0x0B00`–`0x0BFF` | Health service |
//! | `0x0C00`–`0x0CFF` | System Discovery service |
//! | `0x0D00`–`0x0DFF` | Raft Consensus service |
//! | `0x0E00`–`0x0EFF` | Maintenance service |
//! | `0x0F00`–`0x0FFF` | Lease service |

// ---------------------------------------------------------------------------
// Reserved-range opcodes (0x0000–0x000F)
// ---------------------------------------------------------------------------

/// Reserved opcode: handshake request (server→client during connection setup).
///
/// Note: Phase 0.0.A.5 (ALPN-based version negotiation) will likely supersede
/// this — version is exchanged via QUIC ALPN at connection establishment.
/// Reserved here to keep the slot available pending the ALPN design pass.
pub const OPCODE_HANDSHAKE_REQUEST: u16 = 0x0001;

/// Reserved opcode: connection-keepalive ping.
pub const OPCODE_PING: u16 = 0x0002;

/// Reserved opcode: first frame on a new connection; carries the JWT.
/// Server validates and caches caller identity per-connection.
pub const OPCODE_AUTH_ESTABLISH: u16 = 0x0003;

/// Reserved opcode: client-initiated JWT refresh mid-connection (when token
/// expiry approaches). Old token remains valid until response received.
pub const OPCODE_AUTH_REFRESH: u16 = 0x0004;

/// Reserved opcode: protocol-level reflection. Returns the opcode registry as
/// `Vec<(opcode, name, request_type, response_type)>` for `wire-probe` and
/// other introspection tools. Implementation in Phase 0.0.D.
pub const OPCODE_REFLECT: u16 = 0x0005;

// 0x0006-0x000F intentionally unallocated; reserved for future protocol-
// level operations.

// ---------------------------------------------------------------------------
// Range boundaries
// ---------------------------------------------------------------------------

/// Boundary for the reserved opcode range (exclusive upper bound).
pub const RESERVED_RANGE_END: u16 = 0x0010;

/// Per-service opcode range size. Each service is allocated 256 opcodes
/// (sufficient for ~256 RPCs per service; current usage is ~10/service).
pub const SERVICE_RANGE_SIZE: u16 = 0x0100;

/// One past the last opcode in the allocated service space.
///
/// Currently `LEASE_SERVICE_BASE + SERVICE_RANGE_SIZE = 0x1000`. When a new
/// service is allocated above `LEASE_SERVICE_BASE`, this constant must be
/// updated to match — `is_valid_opcode` and the test
/// `is_valid_opcode_rejects_above_allocated` both depend on it.
pub const OPCODE_SPACE_END: u16 = 0x1000;

// ---------------------------------------------------------------------------
// Per-service base opcodes
// ---------------------------------------------------------------------------

/// Starting opcode for the Read service (`0x0010`–`0x00FF`).
///
/// Note: Read shares the first 256-opcode block with the reserved range
/// (`0x0000`–`0x000F`); its base is not a multiple of `SERVICE_RANGE_SIZE`.
/// All other services have their own dedicated 256-opcode block.
pub const READ_SERVICE_BASE: u16 = 0x0010;
/// Starting opcode for the Write service (`0x0100`–`0x01FF`).
pub const WRITE_SERVICE_BASE: u16 = 0x0100;
/// Starting opcode for the Organization service (`0x0200`–`0x02FF`).
pub const ORGANIZATION_SERVICE_BASE: u16 = 0x0200;
/// Starting opcode for the Vault service (`0x0300`–`0x03FF`).
pub const VAULT_SERVICE_BASE: u16 = 0x0300;
/// Starting opcode for the Schema service (`0x0400`–`0x04FF`).
pub const SCHEMA_SERVICE_BASE: u16 = 0x0400;
/// Starting opcode for the User service (`0x0500`–`0x05FF`).
pub const USER_SERVICE_BASE: u16 = 0x0500;
/// Starting opcode for the App service (`0x0600`–`0x06FF`).
pub const APP_SERVICE_BASE: u16 = 0x0600;
/// Starting opcode for the Invitation service (`0x0700`–`0x07FF`).
pub const INVITATION_SERVICE_BASE: u16 = 0x0700;
/// Starting opcode for the Token service (`0x0800`–`0x08FF`).
pub const TOKEN_SERVICE_BASE: u16 = 0x0800;
/// Starting opcode for the Events service (`0x0900`–`0x09FF`).
pub const EVENTS_SERVICE_BASE: u16 = 0x0900;
/// Starting opcode for the Admin service (`0x0A00`–`0x0AFF`).
pub const ADMIN_SERVICE_BASE: u16 = 0x0A00;
/// Starting opcode for the Health service (`0x0B00`–`0x0BFF`).
pub const HEALTH_SERVICE_BASE: u16 = 0x0B00;
/// Starting opcode for the System Discovery service (`0x0C00`–`0x0CFF`).
pub const SYSTEM_DISCOVERY_SERVICE_BASE: u16 = 0x0C00;
/// Starting opcode for the Raft Consensus service (`0x0D00`–`0x0DFF`).
pub const RAFT_CONSENSUS_SERVICE_BASE: u16 = 0x0D00;
/// Opcode for `RaftService::install_snapshot_stream`. The wire-macro DSL
/// declares this RPC as a unary placeholder; at runtime the dispatcher
/// recognises this opcode and routes the bidi stream to the snapshot
/// streaming sub-protocol implemented in
/// `inferadb_ledger_wire_transport::snapshot_stream`. See E.6a.
pub const OPCODE_INSTALL_SNAPSHOT_STREAM: u16 = 0x0D03;
/// Opcode for the Raft inter-node protocol-version handshake (A7).
///
/// Sent as the first frame on every long-lived `Replicate` stream. Carries
/// the sender's [`crate::version::RAFT_PROTOCOL_VERSION`]; the receiver
/// closes the QUIC connection if the value does not match its own. Lands
/// the version-gate at connection establishment, before any replication
/// frame, so a mixed-version cluster cannot exchange Raft state mid-stream.
///
/// Used by Phase 0.0.E.6b's `WireConsensusTransport`. Not invoked from the
/// wire-macro `Dispatcher` path — handled by the per-peer stream loop.
pub const OPCODE_RAFT_PROTOCOL_HANDSHAKE: u16 = 0x0D04;
/// Starting opcode for the Maintenance service (`0x0E00`–`0x0EFF`).
pub const MAINTENANCE_SERVICE_BASE: u16 = 0x0E00;
/// Starting opcode for the Lease service (`0x0F00`–`0x0FFF`).
pub const LEASE_SERVICE_BASE: u16 = 0x0F00;

// ---------------------------------------------------------------------------
// Opcode validity
// ---------------------------------------------------------------------------

/// Returns true if `opcode` is a syntactically valid value in the wire
/// protocol's opcode space.
///
/// This stub accepts:
/// - Any reserved opcode (`0x0001`–`0x000F`)
/// - Any opcode in any allocated service range (`0x0010`–`0x0FFF`)
///
/// It does NOT verify that the opcode corresponds to a registered RPC —
/// that check requires the macro-generated registry from Phase 0.0.D and
/// will replace this stub.
///
/// Opcode `0x0000` is reserved as the "null" / unset value and is rejected.
#[must_use]
pub fn is_valid_opcode(opcode: u16) -> bool {
    // 0x0000 is the null/unset opcode; reject.
    // 0x0001-0x0FFF are the currently-allocated ranges (16 services × 256).
    // 0x1000+ is reserved for future expansion.
    opcode != 0 && opcode < OPCODE_SPACE_END
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn reserved_opcodes_are_distinct() {
        let opcodes = [
            OPCODE_HANDSHAKE_REQUEST,
            OPCODE_PING,
            OPCODE_AUTH_ESTABLISH,
            OPCODE_AUTH_REFRESH,
            OPCODE_REFLECT,
        ];
        for i in 0..opcodes.len() {
            for j in (i + 1)..opcodes.len() {
                assert_ne!(
                    opcodes[i], opcodes[j],
                    "opcodes[{i}] == opcodes[{j}] (both are {:#06X})",
                    opcodes[i]
                );
            }
        }
    }

    #[test]
    fn reserved_opcodes_in_reserved_range() {
        let opcodes = [
            OPCODE_HANDSHAKE_REQUEST,
            OPCODE_PING,
            OPCODE_AUTH_ESTABLISH,
            OPCODE_AUTH_REFRESH,
            OPCODE_REFLECT,
        ];
        for opcode in opcodes {
            assert!(
                opcode < RESERVED_RANGE_END,
                "opcode {opcode:#06X} is not < RESERVED_RANGE_END ({RESERVED_RANGE_END:#06X})"
            );
        }
    }

    #[test]
    fn service_bases_distinct() {
        let bases = [
            READ_SERVICE_BASE,
            WRITE_SERVICE_BASE,
            ORGANIZATION_SERVICE_BASE,
            VAULT_SERVICE_BASE,
            SCHEMA_SERVICE_BASE,
            USER_SERVICE_BASE,
            APP_SERVICE_BASE,
            INVITATION_SERVICE_BASE,
            TOKEN_SERVICE_BASE,
            EVENTS_SERVICE_BASE,
            ADMIN_SERVICE_BASE,
            HEALTH_SERVICE_BASE,
            SYSTEM_DISCOVERY_SERVICE_BASE,
            RAFT_CONSENSUS_SERVICE_BASE,
            MAINTENANCE_SERVICE_BASE,
            LEASE_SERVICE_BASE,
        ];
        for i in 0..bases.len() {
            for j in (i + 1)..bases.len() {
                assert_ne!(
                    bases[i], bases[j],
                    "bases[{i}] == bases[{j}] (both are {:#06X})",
                    bases[i]
                );
            }
        }
    }

    #[test]
    fn service_bases_in_their_range() {
        // READ_SERVICE_BASE starts at 0x0010, sharing the first 256-opcode
        // block with the reserved range (0x0000–0x000F). It is the only
        // service whose base is not a multiple of SERVICE_RANGE_SIZE; all
        // other services begin at clean SERVICE_RANGE_SIZE-aligned offsets.
        assert_eq!(
            READ_SERVICE_BASE, RESERVED_RANGE_END,
            "READ_SERVICE_BASE must immediately follow the reserved range"
        );

        let aligned_bases = [
            WRITE_SERVICE_BASE,
            ORGANIZATION_SERVICE_BASE,
            VAULT_SERVICE_BASE,
            SCHEMA_SERVICE_BASE,
            USER_SERVICE_BASE,
            APP_SERVICE_BASE,
            INVITATION_SERVICE_BASE,
            TOKEN_SERVICE_BASE,
            EVENTS_SERVICE_BASE,
            ADMIN_SERVICE_BASE,
            HEALTH_SERVICE_BASE,
            SYSTEM_DISCOVERY_SERVICE_BASE,
            RAFT_CONSENSUS_SERVICE_BASE,
            MAINTENANCE_SERVICE_BASE,
            LEASE_SERVICE_BASE,
        ];
        for base in aligned_bases {
            assert_eq!(
                base % SERVICE_RANGE_SIZE,
                0,
                "service base {base:#06X} is not a multiple of SERVICE_RANGE_SIZE ({SERVICE_RANGE_SIZE:#06X})"
            );
        }
    }

    #[test]
    fn service_bases_above_reserved() {
        let bases = [
            READ_SERVICE_BASE,
            WRITE_SERVICE_BASE,
            ORGANIZATION_SERVICE_BASE,
            VAULT_SERVICE_BASE,
            SCHEMA_SERVICE_BASE,
            USER_SERVICE_BASE,
            APP_SERVICE_BASE,
            INVITATION_SERVICE_BASE,
            TOKEN_SERVICE_BASE,
            EVENTS_SERVICE_BASE,
            ADMIN_SERVICE_BASE,
            HEALTH_SERVICE_BASE,
            SYSTEM_DISCOVERY_SERVICE_BASE,
            RAFT_CONSENSUS_SERVICE_BASE,
            MAINTENANCE_SERVICE_BASE,
            LEASE_SERVICE_BASE,
        ];
        for base in bases {
            assert!(
                base >= RESERVED_RANGE_END,
                "service base {base:#06X} is below RESERVED_RANGE_END ({RESERVED_RANGE_END:#06X})"
            );
        }
    }

    #[test]
    fn is_valid_opcode_rejects_zero() {
        assert!(!is_valid_opcode(0));
    }

    #[test]
    fn is_valid_opcode_accepts_reserved_range() {
        assert!(is_valid_opcode(OPCODE_PING));
        assert!(is_valid_opcode(OPCODE_AUTH_ESTABLISH));
    }

    #[test]
    fn is_valid_opcode_accepts_service_ranges() {
        assert!(is_valid_opcode(0x0010)); // read service start
        assert!(is_valid_opcode(0x0F00)); // lease service start
        assert!(is_valid_opcode(0x0FFF)); // last allocated value
    }

    #[test]
    fn is_valid_opcode_rejects_above_allocated() {
        assert!(!is_valid_opcode(OPCODE_SPACE_END));
        assert!(!is_valid_opcode(0xFFFF));
    }

    #[test]
    fn reserved_range_end_is_sixteen() {
        assert_eq!(
            RESERVED_RANGE_END, 0x0010,
            "reserved range boundary moved — update service bases"
        );
    }

    #[test]
    fn is_valid_opcode_accepts_unallocated_reserved_slots() {
        // 0x0006-0x000F are reserved but unallocated; syntactically valid.
        assert!(is_valid_opcode(0x0006));
        assert!(is_valid_opcode(0x000F));
    }

    // Compile-time invariants for raft-range opcodes. Using `const { assert!(_) }`
    // (workspace convention) instead of runtime `assert!` inside `#[test]`,
    // since both sides are compile-time constants and clippy
    // `assertions_on_constants` correctly flags the runtime form.
    const _: () = assert!(OPCODE_INSTALL_SNAPSHOT_STREAM >= RAFT_CONSENSUS_SERVICE_BASE);
    const _: () =
        assert!(OPCODE_INSTALL_SNAPSHOT_STREAM < RAFT_CONSENSUS_SERVICE_BASE + SERVICE_RANGE_SIZE);
    const _: () = assert!(OPCODE_RAFT_PROTOCOL_HANDSHAKE >= RAFT_CONSENSUS_SERVICE_BASE);
    const _: () =
        assert!(OPCODE_RAFT_PROTOCOL_HANDSHAKE < RAFT_CONSENSUS_SERVICE_BASE + SERVICE_RANGE_SIZE);
    const _: () = assert!(OPCODE_RAFT_PROTOCOL_HANDSHAKE != OPCODE_INSTALL_SNAPSHOT_STREAM);
}
