//! Centralized proto conversion functions.
//!
//! Provides `From` and `Into` implementations for converting between domain
//! types (from `inferadb_ledger_types`) and proto types (generated by prost).
//!
//! # Design
//!
//! Rather than scattering `foo_to_proto` and `proto_to_foo` functions across
//! service files, all conversions are centralized here using Rust's `From` trait.
//! Enables idiomatic `.into()` calls and ensures consistent, tested conversions.
//!
//! # Usage
//!
//! ```no_run
//! # use inferadb_ledger_proto::{proto, convert};
//! # use inferadb_ledger_types::LedgerNodeId;
//! # use openraft::Vote;
//! // Domain to proto
//! let domain_vote = Vote::new(1u64, 42u64);
//! let proto_vote: proto::RaftVote = domain_vote.into();
//!
//! // Proto to domain
//! let proto_vote = proto::RaftVote { term: 1, node_id: 42, committed: false };
//! let domain_vote: Vote<LedgerNodeId> = proto_vote.into();
//! ```
//!
//! # Note
//!
//! The `OrganizationStatus` conversion lives in the `raft` crate because it
//! depends on `inferadb_ledger_state::system::OrganizationStatus`.

mod credentials;
mod domain;
mod identifiers;
mod operations;
mod raft;
mod statuses;
mod tokens;

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used, clippy::panic, clippy::disallowed_methods)]
mod tests;

// Re-export all public items to preserve the flat `convert::` API.
pub use credentials::{
    credential_type_from_i32, strip_recovery_code_hashes, strip_totp_secret,
    totp_algorithm_from_i32, user_credential_to_proto, validate_credential_info_type,
};
pub use domain::{
    datetime_to_proto_timestamp, proto_timestamp_to_datetime, vault_entry_to_proto_block,
};
pub use statuses::{
    invitation_status_from_i32, region_from_i32, signing_key_scope_from_i32, user_role_from_i32,
    user_status_from_i32, validate_signing_key_status,
};
