//! Wire-based OrganizationService ops.
//!
//! Mirrors [`super::super::ops::organization`]: same returned domain types
//! ([`OrganizationInfo`], [`OrganizationDeleteInfo`], [`OrganizationMemberInfo`],
//! [`TeamInfo`], [`MigrationInfo`]), same `Result<_, SdkError>` shape on the
//! consumer side. Internal dispatch goes through the wire-services-generated
//! [`OrganizationServiceClient`](inferadb_ledger_wire_services::OrganizationServiceClient)
//! instead of the proto-generated tonic client.
//!
//! End-to-end coverage with a real `WireClient` + `WireServer` is deferred
//! to E.7 (TestCluster migration); the unit tests in this file cover the
//! wire-response → domain-type mapping (status / tier / role enums, page
//! envelopes, optional `Team` / `OrganizationMember` unwrap) in isolation.
//! The seventeen per-RPC entry points themselves are not exercised yet —
//! [`LedgerClient`](crate::LedgerClient) keeps dispatching through the tonic
//! `ops::organization` path until F.1 flips the connection pool.

use std::{str::FromStr, sync::Arc};

use bytes::Bytes;
use inferadb_ledger_types::{OrganizationSlug, Region, TeamSlug, UserSlug};
use inferadb_ledger_wire::services::{organization as w, shared as ws};
use inferadb_ledger_wire_services::OrganizationServiceClient;
use inferadb_ledger_wire_transport::WireClient;

use crate::{
    error::{Result, SdkError},
    ops_wire::rpc_error_to_sdk_error,
    types::admin::{
        MigrationInfo, OrganizationDeleteInfo, OrganizationInfo, OrganizationMemberInfo,
        OrganizationMemberRole, OrganizationStatus, OrganizationTier, TeamInfo, TeamMemberInfo,
        TeamMemberRole,
    },
};

// ---------------------------------------------------------------------------
// Organization CRUD
// ---------------------------------------------------------------------------

/// Issue a `CreateOrganization` RPC via the wire transport.
///
/// Mirrors [`LedgerClient::create_organization`](crate::LedgerClient::create_organization)
/// at the dispatch layer. The organization slug is generated by the caller
/// (one slug per logical call, reused across retries) so the server-side
/// idempotency-by-slug path returns the same `OrganizationId` instead of
/// creating a duplicate body on response-lost-in-flight. `request_id` is the
/// 128-bit frame-header correlation ID; the SDK's retry loop is responsible
/// for rotating it across attempts.
///
/// # Errors
///
/// Returns [`SdkError::Connection`] for transport / protocol failures and
/// the appropriate [`SdkError`] variant for server-returned [`WireError`]s
/// (rate-limit family, migration codes, all others land in `Rpc`).
pub(crate) async fn create_organization(
    wire_client: Arc<WireClient>,
    request_id: u128,
    name: String,
    region: Region,
    caller: UserSlug,
    tier: OrganizationTier,
    organization_slug: OrganizationSlug,
) -> Result<OrganizationInfo> {
    let client = OrganizationServiceClient::new(wire_client);
    let request = w::CreateOrganizationRequest {
        name,
        region: region.as_str().to_owned(),
        tier: Some(domain_tier_to_wire(tier)),
        caller: Some(caller),
        slug: Some(organization_slug),
    };
    let response =
        client.create_organization(request, request_id).await.map_err(rpc_error_to_sdk_error)?;
    Ok(domain_organization_info_from_wire_create(response))
}

/// Issue a `GetOrganization` RPC via the wire transport.
///
/// Mirrors [`LedgerClient::get_organization`](crate::LedgerClient::get_organization).
/// Returns the full [`OrganizationInfo`] populated from the
/// `GetOrganizationResponse`.
///
/// # Errors
///
/// Same shape as [`create_organization`].
pub(crate) async fn get_organization(
    wire_client: Arc<WireClient>,
    request_id: u128,
    slug: OrganizationSlug,
    caller: UserSlug,
) -> Result<OrganizationInfo> {
    let client = OrganizationServiceClient::new(wire_client);
    let request = w::GetOrganizationRequest { slug: Some(slug), caller: Some(caller) };
    let response =
        client.get_organization(request, request_id).await.map_err(rpc_error_to_sdk_error)?;
    Ok(domain_organization_info_from_wire_get(response))
}

/// Issue an `UpdateOrganization` RPC via the wire transport.
///
/// Mirrors [`LedgerClient::update_organization`](crate::LedgerClient::update_organization).
/// `name = None` keeps the current name. Returns the updated
/// [`OrganizationInfo`].
///
/// # Errors
///
/// Same shape as [`create_organization`].
pub(crate) async fn update_organization(
    wire_client: Arc<WireClient>,
    request_id: u128,
    slug: OrganizationSlug,
    caller: UserSlug,
    name: Option<String>,
) -> Result<OrganizationInfo> {
    let client = OrganizationServiceClient::new(wire_client);
    let request = w::UpdateOrganizationRequest { slug: Some(slug), caller: Some(caller), name };
    let response =
        client.update_organization(request, request_id).await.map_err(rpc_error_to_sdk_error)?;
    Ok(domain_organization_info_from_wire_update(response))
}

/// Issue a `DeleteOrganization` RPC via the wire transport.
///
/// Mirrors [`LedgerClient::delete_organization`](crate::LedgerClient::delete_organization).
/// The wire response carries a `deleted_at` UNIX-nanoseconds timestamp plus
/// `retention_days`.
///
/// # Errors
///
/// Same shape as [`create_organization`].
pub(crate) async fn delete_organization(
    wire_client: Arc<WireClient>,
    request_id: u128,
    slug: OrganizationSlug,
    caller: UserSlug,
) -> Result<OrganizationDeleteInfo> {
    let client = OrganizationServiceClient::new(wire_client);
    let request = w::DeleteOrganizationRequest { slug: Some(slug), caller: Some(caller) };
    let response =
        client.delete_organization(request, request_id).await.map_err(rpc_error_to_sdk_error)?;
    Ok(OrganizationDeleteInfo {
        deleted_at: nanos_to_system_time(response.deleted_at),
        retention_days: response.retention_days,
    })
}

/// Issue a `ListOrganizations` RPC via the wire transport.
///
/// Mirrors [`LedgerClient::list_organizations`](crate::LedgerClient::list_organizations).
/// Returns a tuple `(organizations, next_page_token)` where
/// `next_page_token` is `None` when there are no more pages. The SDK
/// exposes the page token as `Vec<u8>` even though the wire type uses
/// `Bytes` — the boundary conversion happens here.
///
/// # Errors
///
/// Same shape as [`create_organization`].
pub(crate) async fn list_organizations(
    wire_client: Arc<WireClient>,
    request_id: u128,
    caller: UserSlug,
    page_size: u32,
    page_token: Option<Vec<u8>>,
) -> Result<(Vec<OrganizationInfo>, Option<Vec<u8>>)> {
    let client = OrganizationServiceClient::new(wire_client);
    let request = w::ListOrganizationsRequest {
        page_token: page_token.map(Bytes::from),
        page_size,
        caller: Some(caller),
    };
    let response =
        client.list_organizations(request, request_id).await.map_err(rpc_error_to_sdk_error)?;
    let organizations =
        response.organizations.into_iter().map(domain_organization_info_from_wire_get).collect();
    let next_page_token = response.next_page_token.map(|b| b.to_vec());
    Ok((organizations, next_page_token))
}

// ---------------------------------------------------------------------------
// Organization members
// ---------------------------------------------------------------------------

/// Issue a `ListOrganizationMembers` RPC via the wire transport.
///
/// Mirrors [`LedgerClient::list_organization_members`](crate::LedgerClient::list_organization_members).
///
/// # Errors
///
/// Same shape as [`create_organization`].
pub(crate) async fn list_organization_members(
    wire_client: Arc<WireClient>,
    request_id: u128,
    slug: OrganizationSlug,
    caller: UserSlug,
    page_size: u32,
    page_token: Option<Vec<u8>>,
) -> Result<(Vec<OrganizationMemberInfo>, Option<Vec<u8>>)> {
    let client = OrganizationServiceClient::new(wire_client);
    let request = w::ListOrganizationMembersRequest {
        slug: Some(slug),
        caller: Some(caller),
        page_token: page_token.map(Bytes::from),
        page_size,
    };
    let response = client
        .list_organization_members(request, request_id)
        .await
        .map_err(rpc_error_to_sdk_error)?;
    let members =
        response.members.into_iter().map(domain_organization_member_info_from_wire).collect();
    let next_page_token = response.next_page_token.map(|b| b.to_vec());
    Ok((members, next_page_token))
}

/// Issue a `RemoveOrganizationMember` RPC via the wire transport.
///
/// Mirrors [`LedgerClient::remove_organization_member`](crate::LedgerClient::remove_organization_member).
///
/// # Errors
///
/// Same shape as [`create_organization`].
pub(crate) async fn remove_organization_member(
    wire_client: Arc<WireClient>,
    request_id: u128,
    slug: OrganizationSlug,
    caller: UserSlug,
    target: UserSlug,
) -> Result<()> {
    let client = OrganizationServiceClient::new(wire_client);
    let request = w::RemoveOrganizationMemberRequest {
        slug: Some(slug),
        caller: Some(caller),
        target: Some(target),
    };
    client.remove_organization_member(request, request_id).await.map_err(rpc_error_to_sdk_error)?;
    Ok(())
}

/// Issue an `UpdateOrganizationMemberRole` RPC via the wire transport.
///
/// Mirrors [`LedgerClient::update_organization_member_role`](crate::LedgerClient::update_organization_member_role).
///
/// # Errors
///
/// Returns [`SdkError::Rpc`] with
/// [`ErrorCode::Internal`](inferadb_ledger_wire::ErrorCode::Internal) if the response envelope is
/// missing the `member` field; otherwise same as [`create_organization`].
pub(crate) async fn update_organization_member_role(
    wire_client: Arc<WireClient>,
    request_id: u128,
    slug: OrganizationSlug,
    caller: UserSlug,
    target: UserSlug,
    role: OrganizationMemberRole,
) -> Result<OrganizationMemberInfo> {
    let client = OrganizationServiceClient::new(wire_client);
    let request = w::UpdateOrganizationMemberRoleRequest {
        slug: Some(slug),
        caller: Some(caller),
        target: Some(target),
        role: domain_member_role_to_wire(role),
    };
    let response = client
        .update_organization_member_role(request, request_id)
        .await
        .map_err(rpc_error_to_sdk_error)?;
    response
        .member
        .map(domain_organization_member_info_from_wire)
        .ok_or_else(|| missing_field("member", "UpdateOrganizationMemberRoleResponse"))
}

// ---------------------------------------------------------------------------
// Organization teams
// ---------------------------------------------------------------------------

/// Issue a `ListOrganizationTeams` RPC via the wire transport.
///
/// Mirrors [`LedgerClient::list_organization_teams`](crate::LedgerClient::list_organization_teams).
///
/// # Errors
///
/// Same shape as [`create_organization`].
pub(crate) async fn list_organization_teams(
    wire_client: Arc<WireClient>,
    request_id: u128,
    organization: OrganizationSlug,
    caller: UserSlug,
    page_size: u32,
    page_token: Option<Vec<u8>>,
) -> Result<(Vec<TeamInfo>, Option<Vec<u8>>)> {
    let client = OrganizationServiceClient::new(wire_client);
    let request = w::ListOrganizationTeamsRequest {
        organization: Some(organization),
        caller: Some(caller),
        page_token: page_token.map(Bytes::from),
        page_size,
    };
    let response = client
        .list_organization_teams(request, request_id)
        .await
        .map_err(rpc_error_to_sdk_error)?;
    let teams = response.teams.into_iter().map(domain_team_info_from_wire).collect();
    let next_page_token = response.next_page_token.map(|b| b.to_vec());
    Ok((teams, next_page_token))
}

/// Issue a `CreateOrganizationTeam` RPC via the wire transport.
///
/// Mirrors [`LedgerClient::create_organization_team`](crate::LedgerClient::create_organization_team).
/// The team slug is generated by the caller — every retry reuses it so
/// the server's apply idempotency-by-slug path returns the same `TeamId`
/// instead of creating a duplicate directory entry on
/// response-lost-in-flight.
///
/// # Errors
///
/// Returns [`SdkError::Rpc`] with
/// [`ErrorCode::Internal`](inferadb_ledger_wire::ErrorCode::Internal) if the response envelope is
/// missing the `team` field; otherwise same as [`create_organization`].
pub(crate) async fn create_organization_team(
    wire_client: Arc<WireClient>,
    request_id: u128,
    organization: OrganizationSlug,
    name: String,
    caller: UserSlug,
    team_slug: TeamSlug,
) -> Result<TeamInfo> {
    let client = OrganizationServiceClient::new(wire_client);
    let request = w::CreateOrganizationTeamRequest {
        organization: Some(organization),
        name,
        caller: Some(caller),
        slug: Some(team_slug),
    };
    let response = client
        .create_organization_team(request, request_id)
        .await
        .map_err(rpc_error_to_sdk_error)?;
    response
        .team
        .map(domain_team_info_from_wire)
        .ok_or_else(|| missing_field("team", "CreateOrganizationTeamResponse"))
}

/// Issue a `DeleteOrganizationTeam` RPC via the wire transport.
///
/// Mirrors [`LedgerClient::delete_organization_team`](crate::LedgerClient::delete_organization_team).
/// `move_members_to` optionally relocates members to another team before
/// deletion.
///
/// # Errors
///
/// Same shape as [`create_organization`].
pub(crate) async fn delete_organization_team(
    wire_client: Arc<WireClient>,
    request_id: u128,
    team: TeamSlug,
    caller: UserSlug,
    move_members_to: Option<TeamSlug>,
) -> Result<()> {
    let client = OrganizationServiceClient::new(wire_client);
    let request = w::DeleteOrganizationTeamRequest {
        slug: Some(team),
        move_members_to,
        caller: Some(caller),
    };
    client.delete_organization_team(request, request_id).await.map_err(rpc_error_to_sdk_error)?;
    Ok(())
}

/// Issue an `UpdateOrganizationTeam` RPC via the wire transport.
///
/// Mirrors [`LedgerClient::update_organization_team`](crate::LedgerClient::update_organization_team).
///
/// # Errors
///
/// Returns [`SdkError::Rpc`] with
/// [`ErrorCode::Internal`](inferadb_ledger_wire::ErrorCode::Internal) if the response envelope is
/// missing the `team` field; otherwise same as [`create_organization`].
pub(crate) async fn update_organization_team(
    wire_client: Arc<WireClient>,
    request_id: u128,
    team: TeamSlug,
    caller: UserSlug,
    name: Option<String>,
) -> Result<TeamInfo> {
    let client = OrganizationServiceClient::new(wire_client);
    let request = w::UpdateOrganizationTeamRequest { slug: Some(team), caller: Some(caller), name };
    let response = client
        .update_organization_team(request, request_id)
        .await
        .map_err(rpc_error_to_sdk_error)?;
    response
        .team
        .map(domain_team_info_from_wire)
        .ok_or_else(|| missing_field("team", "UpdateOrganizationTeamResponse"))
}

/// Issue a `GetOrganizationTeam` RPC via the wire transport.
///
/// Mirrors [`LedgerClient::get_organization_team`](crate::LedgerClient::get_organization_team).
///
/// # Errors
///
/// Returns [`SdkError::Rpc`] with
/// [`ErrorCode::Internal`](inferadb_ledger_wire::ErrorCode::Internal) if the response envelope is
/// missing the `team` field; otherwise same as [`create_organization`].
pub(crate) async fn get_organization_team(
    wire_client: Arc<WireClient>,
    request_id: u128,
    team: TeamSlug,
    caller: UserSlug,
) -> Result<TeamInfo> {
    let client = OrganizationServiceClient::new(wire_client);
    let request = w::GetOrganizationTeamRequest { slug: Some(team), caller: Some(caller) };
    let response =
        client.get_organization_team(request, request_id).await.map_err(rpc_error_to_sdk_error)?;
    response
        .team
        .map(domain_team_info_from_wire)
        .ok_or_else(|| missing_field("team", "GetOrganizationTeamResponse"))
}

// ---------------------------------------------------------------------------
// Team members
// ---------------------------------------------------------------------------

/// Issue an `AddTeamMember` RPC via the wire transport.
///
/// Mirrors [`LedgerClient::add_team_member`](crate::LedgerClient::add_team_member).
/// Returns the updated [`TeamInfo`].
///
/// # Errors
///
/// Returns [`SdkError::Rpc`] with
/// [`ErrorCode::Internal`](inferadb_ledger_wire::ErrorCode::Internal) if the response envelope is
/// missing the `team` field; otherwise same as [`create_organization`].
pub(crate) async fn add_team_member(
    wire_client: Arc<WireClient>,
    request_id: u128,
    team: TeamSlug,
    user: UserSlug,
    role: TeamMemberRole,
    caller: UserSlug,
) -> Result<TeamInfo> {
    let client = OrganizationServiceClient::new(wire_client);
    let request = w::AddTeamMemberRequest {
        team: Some(team),
        user: Some(user),
        role: domain_team_role_to_wire(role),
        caller: Some(caller),
    };
    let response =
        client.add_team_member(request, request_id).await.map_err(rpc_error_to_sdk_error)?;
    response
        .team
        .map(domain_team_info_from_wire)
        .ok_or_else(|| missing_field("team", "AddTeamMemberResponse"))
}

/// Issue a `RemoveTeamMember` RPC via the wire transport.
///
/// Mirrors [`LedgerClient::remove_team_member`](crate::LedgerClient::remove_team_member).
///
/// # Errors
///
/// Same shape as [`create_organization`].
pub(crate) async fn remove_team_member(
    wire_client: Arc<WireClient>,
    request_id: u128,
    team: TeamSlug,
    user: UserSlug,
    caller: UserSlug,
) -> Result<()> {
    let client = OrganizationServiceClient::new(wire_client);
    let request =
        w::RemoveTeamMemberRequest { team: Some(team), user: Some(user), caller: Some(caller) };
    client.remove_team_member(request, request_id).await.map_err(rpc_error_to_sdk_error)?;
    Ok(())
}

/// Issue an `UpdateTeamMemberRole` RPC via the wire transport.
///
/// Mirrors [`LedgerClient::update_team_member_role`](crate::LedgerClient::update_team_member_role).
///
/// # Errors
///
/// Returns [`SdkError::Rpc`] with
/// [`ErrorCode::Internal`](inferadb_ledger_wire::ErrorCode::Internal) if the response envelope is
/// missing the `team` field; otherwise same as [`create_organization`].
pub(crate) async fn update_team_member_role(
    wire_client: Arc<WireClient>,
    request_id: u128,
    team: TeamSlug,
    user: UserSlug,
    role: TeamMemberRole,
    caller: UserSlug,
) -> Result<TeamInfo> {
    let client = OrganizationServiceClient::new(wire_client);
    let request = w::UpdateTeamMemberRoleRequest {
        team: Some(team),
        user: Some(user),
        role: domain_team_role_to_wire(role),
        caller: Some(caller),
    };
    let response = client
        .update_team_member_role(request, request_id)
        .await
        .map_err(rpc_error_to_sdk_error)?;
    response
        .team
        .map(domain_team_info_from_wire)
        .ok_or_else(|| missing_field("team", "UpdateTeamMemberRoleResponse"))
}

// ---------------------------------------------------------------------------
// Organization migration
// ---------------------------------------------------------------------------

/// Issue a `MigrateOrganization` RPC via the wire transport.
///
/// Mirrors [`LedgerClient::migrate_organization`](crate::LedgerClient::migrate_organization).
/// Returns [`MigrationInfo`] with source / target regions and current
/// status. The wire response carries `source_region` / `target_region` as
/// region-slug strings; this helper falls back to `Region::GLOBAL` /
/// caller-provided `target_region` when the slug doesn't parse — same
/// fail-soft contract as the proto path.
///
/// # Errors
///
/// Same shape as [`create_organization`].
pub(crate) async fn migrate_organization(
    wire_client: Arc<WireClient>,
    request_id: u128,
    slug: OrganizationSlug,
    target_region: Region,
    acknowledge_residency_downgrade: bool,
    caller: UserSlug,
) -> Result<MigrationInfo> {
    let client = OrganizationServiceClient::new(wire_client);
    let request = w::MigrateOrganizationRequest {
        slug: Some(slug),
        target_region: target_region.as_str().to_owned(),
        acknowledge_residency_downgrade,
        caller: Some(caller),
    };
    let response =
        client.migrate_organization(request, request_id).await.map_err(rpc_error_to_sdk_error)?;
    Ok(MigrationInfo {
        slug: response.slug.unwrap_or_else(|| OrganizationSlug::new(0)),
        source_region: parse_region(&response.source_region).unwrap_or(Region::GLOBAL),
        target_region: parse_region(&response.target_region).unwrap_or(target_region),
        status: wire_organization_status_to_domain(response.status),
    })
}

// ---------------------------------------------------------------------------
// Wire → domain mappers
// ---------------------------------------------------------------------------

/// Maps a wire `CreateOrganizationResponse` to the domain
/// [`OrganizationInfo`].
fn domain_organization_info_from_wire_create(
    resp: w::CreateOrganizationResponse,
) -> OrganizationInfo {
    OrganizationInfo {
        slug: resp.slug.unwrap_or_else(|| OrganizationSlug::new(0)),
        name: resp.name,
        region: parse_region(&resp.region).unwrap_or(Region::GLOBAL),
        member_nodes: resp.member_nodes.into_iter().map(|n| n.value().to_owned()).collect(),
        config_version: resp.config_version,
        status: wire_organization_status_to_domain(resp.status),
        tier: wire_organization_tier_to_domain(resp.tier),
        members: resp.members.into_iter().map(domain_organization_member_info_from_wire).collect(),
    }
}

/// Maps a wire `GetOrganizationResponse` to the domain [`OrganizationInfo`].
fn domain_organization_info_from_wire_get(resp: w::GetOrganizationResponse) -> OrganizationInfo {
    OrganizationInfo {
        slug: resp.slug.unwrap_or_else(|| OrganizationSlug::new(0)),
        name: resp.name,
        region: parse_region(&resp.region).unwrap_or(Region::GLOBAL),
        member_nodes: resp.member_nodes.into_iter().map(|n| n.value().to_owned()).collect(),
        config_version: resp.config_version,
        status: wire_organization_status_to_domain(resp.status),
        tier: wire_organization_tier_to_domain(resp.tier),
        members: resp.members.into_iter().map(domain_organization_member_info_from_wire).collect(),
    }
}

/// Maps a wire `UpdateOrganizationResponse` to the domain
/// [`OrganizationInfo`].
fn domain_organization_info_from_wire_update(
    resp: w::UpdateOrganizationResponse,
) -> OrganizationInfo {
    OrganizationInfo {
        slug: resp.slug.unwrap_or_else(|| OrganizationSlug::new(0)),
        name: resp.name,
        region: parse_region(&resp.region).unwrap_or(Region::GLOBAL),
        member_nodes: resp.member_nodes.into_iter().map(|n| n.value().to_owned()).collect(),
        config_version: resp.config_version,
        status: wire_organization_status_to_domain(resp.status),
        tier: wire_organization_tier_to_domain(resp.tier),
        members: resp.members.into_iter().map(domain_organization_member_info_from_wire).collect(),
    }
}

/// Maps a wire `OrganizationMember` to the domain [`OrganizationMemberInfo`].
///
/// Optional `user` defaults to the zero-id newtype on absence — mirrors the
/// `m.user.map_or(0, ...)` pattern in the proto path.
fn domain_organization_member_info_from_wire(m: ws::OrganizationMember) -> OrganizationMemberInfo {
    OrganizationMemberInfo {
        user: m.user.unwrap_or_else(|| UserSlug::new(0)),
        role: wire_member_role_to_domain(m.role),
        joined_at: nanos_to_system_time(m.joined_at),
    }
}

/// Maps a wire `OrganizationTeam` to the domain [`TeamInfo`].
fn domain_team_info_from_wire(t: ws::OrganizationTeam) -> TeamInfo {
    TeamInfo {
        slug: t.slug.unwrap_or_else(|| TeamSlug::new(0)),
        organization: t.organization.unwrap_or_else(|| OrganizationSlug::new(0)),
        name: t.name,
        members: t.members.into_iter().map(domain_team_member_info_from_wire).collect(),
        created_at: nanos_to_system_time(t.created_at),
        updated_at: nanos_to_system_time(t.updated_at),
    }
}

/// Maps a wire `OrganizationTeamMember` to the domain [`TeamMemberInfo`].
fn domain_team_member_info_from_wire(m: ws::OrganizationTeamMember) -> TeamMemberInfo {
    TeamMemberInfo {
        user: m.user.unwrap_or_else(|| UserSlug::new(0)),
        role: wire_team_member_role_to_domain(m.role),
        joined_at: nanos_to_system_time(m.joined_at),
    }
}

// ---------------------------------------------------------------------------
// Enum projections
// ---------------------------------------------------------------------------

/// Numeric-tag mapping from the wire `OrganizationStatus` to the domain
/// enum. Mirrors the proto-side `OrganizationStatus::from_proto(i32)`.
fn wire_organization_status_to_domain(status: ws::OrganizationStatus) -> OrganizationStatus {
    match status {
        ws::OrganizationStatus::Active => OrganizationStatus::Active,
        ws::OrganizationStatus::Provisioning => OrganizationStatus::Provisioning,
        ws::OrganizationStatus::Migrating => OrganizationStatus::Migrating,
        ws::OrganizationStatus::Suspended => OrganizationStatus::Suspended,
        ws::OrganizationStatus::Deleted => OrganizationStatus::Deleted,
        ws::OrganizationStatus::Unspecified => OrganizationStatus::Unspecified,
    }
}

/// Numeric-tag mapping from the wire `OrganizationTier` to the domain
/// enum. Mirrors the proto-side `OrganizationTier::from_proto(i32)` —
/// `Unspecified` collapses to `Free`, matching the proto path's default.
fn wire_organization_tier_to_domain(tier: ws::OrganizationTier) -> OrganizationTier {
    match tier {
        ws::OrganizationTier::Launch => OrganizationTier::Launch,
        ws::OrganizationTier::Scale => OrganizationTier::Scale,
        // Unspecified + Free both surface as Free — mirrors proto path.
        ws::OrganizationTier::Free | ws::OrganizationTier::Unspecified => OrganizationTier::Free,
    }
}

/// Numeric-tag mapping from the domain `OrganizationTier` to the wire
/// enum, used on outgoing requests.
fn domain_tier_to_wire(tier: OrganizationTier) -> ws::OrganizationTier {
    match tier {
        OrganizationTier::Free => ws::OrganizationTier::Free,
        OrganizationTier::Launch => ws::OrganizationTier::Launch,
        OrganizationTier::Scale => ws::OrganizationTier::Scale,
    }
}

/// Numeric-tag mapping from the wire `OrganizationMemberRole` to the
/// domain enum. The wire `Unspecified` and `Member` variants both collapse
/// to `Member` in the domain — matches the proto path.
fn wire_member_role_to_domain(role: ws::OrganizationMemberRole) -> OrganizationMemberRole {
    match role {
        ws::OrganizationMemberRole::Admin => OrganizationMemberRole::Admin,
        ws::OrganizationMemberRole::Member | ws::OrganizationMemberRole::Unspecified => {
            OrganizationMemberRole::Member
        },
    }
}

/// Numeric-tag mapping from the domain `OrganizationMemberRole` to the
/// wire enum, used on outgoing requests.
fn domain_member_role_to_wire(role: OrganizationMemberRole) -> ws::OrganizationMemberRole {
    match role {
        OrganizationMemberRole::Admin => ws::OrganizationMemberRole::Admin,
        OrganizationMemberRole::Member => ws::OrganizationMemberRole::Member,
    }
}

/// Numeric-tag mapping from the wire `OrganizationTeamMemberRole` to the
/// domain enum. The wire `Unspecified` and `Member` variants both collapse
/// to `Member` in the domain — matches the proto path.
fn wire_team_member_role_to_domain(role: ws::OrganizationTeamMemberRole) -> TeamMemberRole {
    match role {
        ws::OrganizationTeamMemberRole::Manager => TeamMemberRole::Manager,
        ws::OrganizationTeamMemberRole::Member | ws::OrganizationTeamMemberRole::Unspecified => {
            TeamMemberRole::Member
        },
    }
}

/// Numeric-tag mapping from the domain `TeamMemberRole` to the wire enum,
/// used on outgoing requests.
fn domain_team_role_to_wire(role: TeamMemberRole) -> ws::OrganizationTeamMemberRole {
    match role {
        TeamMemberRole::Manager => ws::OrganizationTeamMemberRole::Manager,
        TeamMemberRole::Member => ws::OrganizationTeamMemberRole::Member,
    }
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/// Parses a wire-format region slug into a domain [`Region`]. Returns
/// `None` for empty or malformed slugs — callers decide the fallback.
fn parse_region(value: &str) -> Option<Region> {
    Region::from_str(value).ok()
}

/// Converts a UNIX-nanoseconds wire timestamp into `SystemTime`.
///
/// Returns `None` for `0` (the wire convention for "unset") and for values
/// that overflow `Duration`. This mirrors the proto path's
/// `proto_timestamp_to_system_time` which returns `None` on absence /
/// invalid inputs.
fn nanos_to_system_time(nanos: u64) -> Option<std::time::SystemTime> {
    if nanos == 0 {
        return None;
    }
    let secs = nanos / 1_000_000_000;
    let subsec_nanos = u32::try_from(nanos % 1_000_000_000).ok()?;
    std::time::UNIX_EPOCH.checked_add(std::time::Duration::new(secs, subsec_nanos))
}

/// Builds the "missing field" `SdkError` shared by single-record wire
/// responses. Mirrors `proto_util::missing_response_field` at the dispatch
/// layer — same `wire ErrorCode::Internal` shape so SDK consumers see one
/// error shape across both transports.
fn missing_field(field: &str, response_type: &str) -> SdkError {
    SdkError::Rpc {
        code: inferadb_ledger_wire::ErrorCode::Internal,
        message: format!("Missing {field} in {response_type}"),
        request_id: None,
        trace_id: None,
        error_details: None,
    }
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used, clippy::panic, clippy::disallowed_methods)]
mod tests {
    //! Unit coverage for wire-response → domain-type mapping plus the
    //! enum-tag projections in both directions. End-to-end tests against a
    //! real `WireClient` / `WireServer` are deferred to E.7 (TestCluster
    //! migration) — at that point the seventeen per-RPC entry points get
    //! exercised in full.

    use inferadb_ledger_types::NodeId as DomainNodeId;

    use super::*;

    // ----- OrganizationStatus: wire → domain -----

    #[test]
    fn wire_organization_status_each_variant_maps_correctly() {
        assert_eq!(
            wire_organization_status_to_domain(ws::OrganizationStatus::Unspecified),
            OrganizationStatus::Unspecified,
        );
        assert_eq!(
            wire_organization_status_to_domain(ws::OrganizationStatus::Active),
            OrganizationStatus::Active,
        );
        assert_eq!(
            wire_organization_status_to_domain(ws::OrganizationStatus::Provisioning),
            OrganizationStatus::Provisioning,
        );
        assert_eq!(
            wire_organization_status_to_domain(ws::OrganizationStatus::Migrating),
            OrganizationStatus::Migrating,
        );
        assert_eq!(
            wire_organization_status_to_domain(ws::OrganizationStatus::Suspended),
            OrganizationStatus::Suspended,
        );
        assert_eq!(
            wire_organization_status_to_domain(ws::OrganizationStatus::Deleted),
            OrganizationStatus::Deleted,
        );
    }

    #[test]
    fn wire_organization_status_numeric_tags_match_proto() {
        // Wire enum is `#[repr(i32)]`; tags must match proto so the
        // numeric tag flows uninterpreted through the dispatch layer.
        assert_eq!(ws::OrganizationStatus::Unspecified as i32, 0);
        assert_eq!(ws::OrganizationStatus::Active as i32, 1);
        assert_eq!(ws::OrganizationStatus::Migrating as i32, 2);
        assert_eq!(ws::OrganizationStatus::Suspended as i32, 3);
        assert_eq!(ws::OrganizationStatus::Deleted as i32, 4);
        assert_eq!(ws::OrganizationStatus::Provisioning as i32, 5);
    }

    // ----- OrganizationTier: wire → domain -----

    #[test]
    fn wire_organization_tier_each_variant_maps_correctly() {
        assert_eq!(
            wire_organization_tier_to_domain(ws::OrganizationTier::Launch),
            OrganizationTier::Launch,
        );
        assert_eq!(
            wire_organization_tier_to_domain(ws::OrganizationTier::Scale),
            OrganizationTier::Scale,
        );
        // Unspecified and Free both collapse to Free — matches proto path.
        assert_eq!(
            wire_organization_tier_to_domain(ws::OrganizationTier::Free),
            OrganizationTier::Free,
        );
        assert_eq!(
            wire_organization_tier_to_domain(ws::OrganizationTier::Unspecified),
            OrganizationTier::Free,
        );
    }

    #[test]
    fn domain_tier_to_wire_each_variant() {
        assert_eq!(domain_tier_to_wire(OrganizationTier::Free), ws::OrganizationTier::Free);
        assert_eq!(domain_tier_to_wire(OrganizationTier::Launch), ws::OrganizationTier::Launch);
        assert_eq!(domain_tier_to_wire(OrganizationTier::Scale), ws::OrganizationTier::Scale);
    }

    #[test]
    fn wire_organization_tier_numeric_tags_match_proto() {
        assert_eq!(ws::OrganizationTier::Unspecified as i32, 0);
        assert_eq!(ws::OrganizationTier::Free as i32, 1);
        assert_eq!(ws::OrganizationTier::Launch as i32, 2);
        assert_eq!(ws::OrganizationTier::Scale as i32, 3);
    }

    // ----- OrganizationMemberRole -----

    #[test]
    fn wire_member_role_each_variant_maps_correctly() {
        assert_eq!(
            wire_member_role_to_domain(ws::OrganizationMemberRole::Admin),
            OrganizationMemberRole::Admin,
        );
        assert_eq!(
            wire_member_role_to_domain(ws::OrganizationMemberRole::Member),
            OrganizationMemberRole::Member,
        );
        // Unspecified collapses to Member — matches proto path.
        assert_eq!(
            wire_member_role_to_domain(ws::OrganizationMemberRole::Unspecified),
            OrganizationMemberRole::Member,
        );
    }

    #[test]
    fn domain_member_role_to_wire_each_variant() {
        assert_eq!(
            domain_member_role_to_wire(OrganizationMemberRole::Admin),
            ws::OrganizationMemberRole::Admin,
        );
        assert_eq!(
            domain_member_role_to_wire(OrganizationMemberRole::Member),
            ws::OrganizationMemberRole::Member,
        );
    }

    #[test]
    fn wire_org_member_role_numeric_tags_match_proto() {
        assert_eq!(ws::OrganizationMemberRole::Unspecified as i32, 0);
        assert_eq!(ws::OrganizationMemberRole::Admin as i32, 1);
        assert_eq!(ws::OrganizationMemberRole::Member as i32, 2);
    }

    // ----- OrganizationTeamMemberRole -----

    #[test]
    fn wire_team_member_role_each_variant_maps_correctly() {
        assert_eq!(
            wire_team_member_role_to_domain(ws::OrganizationTeamMemberRole::Manager),
            TeamMemberRole::Manager,
        );
        assert_eq!(
            wire_team_member_role_to_domain(ws::OrganizationTeamMemberRole::Member),
            TeamMemberRole::Member,
        );
        // Unspecified collapses to Member — matches proto path.
        assert_eq!(
            wire_team_member_role_to_domain(ws::OrganizationTeamMemberRole::Unspecified),
            TeamMemberRole::Member,
        );
    }

    #[test]
    fn domain_team_role_to_wire_each_variant() {
        assert_eq!(
            domain_team_role_to_wire(TeamMemberRole::Manager),
            ws::OrganizationTeamMemberRole::Manager,
        );
        assert_eq!(
            domain_team_role_to_wire(TeamMemberRole::Member),
            ws::OrganizationTeamMemberRole::Member,
        );
    }

    #[test]
    fn wire_team_member_role_numeric_tags_match_proto() {
        assert_eq!(ws::OrganizationTeamMemberRole::Unspecified as i32, 0);
        assert_eq!(ws::OrganizationTeamMemberRole::Manager as i32, 1);
        assert_eq!(ws::OrganizationTeamMemberRole::Member as i32, 2);
    }

    // ----- nanos_to_system_time -----

    #[test]
    fn nanos_to_system_time_zero_returns_none() {
        // 0 ns is the wire convention for "unset"; matches proto's absent
        // `Timestamp` message.
        assert!(nanos_to_system_time(0).is_none());
    }

    #[test]
    fn nanos_to_system_time_round_trips_known_value() {
        let nanos = 1_700_000_000_500_000_000u64;
        let st = nanos_to_system_time(nanos).expect("known value should convert");
        let d = st.duration_since(std::time::UNIX_EPOCH).expect("after epoch");
        assert_eq!(d.as_secs(), 1_700_000_000);
        assert_eq!(d.subsec_nanos(), 500_000_000);
    }

    // ----- domain_organization_member_info_from_wire -----

    #[test]
    fn organization_member_from_wire_preserves_fields() {
        let m = ws::OrganizationMember {
            user: Some(UserSlug::new(42)),
            role: ws::OrganizationMemberRole::Admin,
            joined_at: 1_700_000_000_000_000_000,
        };
        let info = domain_organization_member_info_from_wire(m);
        assert_eq!(info.user, UserSlug::new(42));
        assert_eq!(info.role, OrganizationMemberRole::Admin);
        assert!(info.joined_at.is_some());
    }

    #[test]
    fn organization_member_missing_user_defaults_to_zero() {
        // Mirrors the proto path's `m.user.map_or(0, ...)` fallback.
        let m = ws::OrganizationMember {
            user: None,
            role: ws::OrganizationMemberRole::Member,
            joined_at: 0,
        };
        let info = domain_organization_member_info_from_wire(m);
        assert_eq!(info.user, UserSlug::new(0));
        assert!(info.joined_at.is_none());
    }

    // ----- domain_team_info_from_wire -----

    #[test]
    fn team_info_from_wire_round_trips_fields() {
        let team = ws::OrganizationTeam {
            slug: Some(TeamSlug::new(11)),
            organization: Some(OrganizationSlug::new(22)),
            name: "engineering".to_owned(),
            members: vec![ws::OrganizationTeamMember {
                user: Some(UserSlug::new(33)),
                role: ws::OrganizationTeamMemberRole::Manager,
                joined_at: 1_700_000_000_000_000_000,
            }],
            created_at: 1_700_000_000_000_000_000,
            updated_at: 1_700_000_001_000_000_000,
        };
        let info = domain_team_info_from_wire(team);
        assert_eq!(info.slug, TeamSlug::new(11));
        assert_eq!(info.organization, OrganizationSlug::new(22));
        assert_eq!(info.name, "engineering");
        assert_eq!(info.members.len(), 1);
        assert_eq!(info.members[0].user, UserSlug::new(33));
        assert_eq!(info.members[0].role, TeamMemberRole::Manager);
        assert!(info.created_at.is_some());
        assert!(info.updated_at.is_some());
    }

    #[test]
    fn team_info_missing_optionals_defaults_safely() {
        let team = ws::OrganizationTeam {
            slug: None,
            organization: None,
            name: String::new(),
            members: vec![],
            created_at: 0,
            updated_at: 0,
        };
        let info = domain_team_info_from_wire(team);
        assert_eq!(info.slug, TeamSlug::new(0));
        assert_eq!(info.organization, OrganizationSlug::new(0));
        assert!(info.members.is_empty());
        assert!(info.created_at.is_none());
        assert!(info.updated_at.is_none());
    }

    // ----- domain_organization_info_from_wire_get -----

    #[test]
    fn organization_info_from_wire_get_round_trips_fields() {
        let resp = w::GetOrganizationResponse {
            slug: Some(OrganizationSlug::new(7)),
            name: "acme".to_owned(),
            region: "us-east-va".to_owned(),
            member_nodes: vec![DomainNodeId::new("node-a"), DomainNodeId::new("node-b")],
            status: ws::OrganizationStatus::Active,
            config_version: 3,
            created_at: 1_700_000_000_000_000_000,
            tier: ws::OrganizationTier::Launch,
            members: vec![ws::OrganizationMember {
                user: Some(UserSlug::new(99)),
                role: ws::OrganizationMemberRole::Admin,
                joined_at: 1_700_000_000_000_000_000,
            }],
            updated_at: 1_700_000_001_000_000_000,
        };
        let info = domain_organization_info_from_wire_get(resp);
        assert_eq!(info.slug, OrganizationSlug::new(7));
        assert_eq!(info.name, "acme");
        assert_eq!(info.member_nodes, vec!["node-a".to_owned(), "node-b".to_owned()]);
        assert_eq!(info.config_version, 3);
        assert_eq!(info.status, OrganizationStatus::Active);
        assert_eq!(info.tier, OrganizationTier::Launch);
        assert_eq!(info.members.len(), 1);
        assert_eq!(info.members[0].user, UserSlug::new(99));
        assert_eq!(info.members[0].role, OrganizationMemberRole::Admin);
    }

    #[test]
    fn organization_info_from_wire_get_missing_optionals_defaults_safely() {
        let resp = w::GetOrganizationResponse {
            slug: None,
            name: String::new(),
            region: String::new(),
            member_nodes: vec![],
            status: ws::OrganizationStatus::Unspecified,
            config_version: 0,
            created_at: 0,
            tier: ws::OrganizationTier::Unspecified,
            members: vec![],
            updated_at: 0,
        };
        let info = domain_organization_info_from_wire_get(resp);
        assert_eq!(info.slug, OrganizationSlug::new(0));
        assert!(info.name.is_empty());
        // Empty region slug doesn't parse — falls back to GLOBAL.
        assert_eq!(info.region, Region::GLOBAL);
        assert!(info.member_nodes.is_empty());
        assert_eq!(info.status, OrganizationStatus::Unspecified);
        // Tier Unspecified collapses to Free.
        assert_eq!(info.tier, OrganizationTier::Free);
        assert!(info.members.is_empty());
    }

    // ----- domain_organization_info_from_wire_create -----

    #[test]
    fn organization_info_from_wire_create_round_trips_fields() {
        let resp = w::CreateOrganizationResponse {
            slug: Some(OrganizationSlug::new(1)),
            name: "newco".to_owned(),
            region: "eu-west-de".to_owned(),
            member_nodes: vec![DomainNodeId::new("node-x")],
            status: ws::OrganizationStatus::Provisioning,
            config_version: 1,
            created_at: 1_700_000_000_000_000_000,
            tier: ws::OrganizationTier::Free,
            members: vec![],
            updated_at: 1_700_000_000_000_000_000,
        };
        let info = domain_organization_info_from_wire_create(resp);
        assert_eq!(info.slug, OrganizationSlug::new(1));
        assert_eq!(info.name, "newco");
        assert_eq!(info.member_nodes, vec!["node-x".to_owned()]);
        assert_eq!(info.status, OrganizationStatus::Provisioning);
        assert_eq!(info.tier, OrganizationTier::Free);
    }

    // ----- domain_organization_info_from_wire_update -----

    #[test]
    fn organization_info_from_wire_update_round_trips_fields() {
        let resp = w::UpdateOrganizationResponse {
            slug: Some(OrganizationSlug::new(2)),
            name: "renamed".to_owned(),
            region: "us-east-va".to_owned(),
            member_nodes: vec![],
            status: ws::OrganizationStatus::Active,
            config_version: 4,
            created_at: 0,
            tier: ws::OrganizationTier::Scale,
            members: vec![],
            updated_at: 0,
        };
        let info = domain_organization_info_from_wire_update(resp);
        assert_eq!(info.slug, OrganizationSlug::new(2));
        assert_eq!(info.name, "renamed");
        assert_eq!(info.status, OrganizationStatus::Active);
        assert_eq!(info.tier, OrganizationTier::Scale);
        assert_eq!(info.config_version, 4);
    }

    // ----- missing_field error shape -----

    #[test]
    fn missing_field_returns_internal_rpc_error() {
        let err = missing_field("team", "GetOrganizationTeamResponse");
        match err {
            SdkError::Rpc { code, message, request_id, trace_id, error_details } => {
                assert_eq!(code, inferadb_ledger_wire::ErrorCode::Internal);
                assert!(message.contains("team"), "got: {message}");
                assert!(message.contains("GetOrganizationTeamResponse"), "got: {message}");
                assert!(message.contains("Missing"), "got: {message}");
                assert!(request_id.is_none());
                assert!(trace_id.is_none());
                assert!(error_details.is_none());
            },
            other => panic!("expected Rpc, got {other:?}"),
        }
    }

    // ----- parse_region -----

    #[test]
    fn parse_region_known_slug_returns_some() {
        assert!(parse_region("us-east-va").is_some());
    }

    #[test]
    fn parse_region_empty_string_returns_none() {
        assert!(parse_region("").is_none());
    }
}
