//! Wire-based vault CRUD ops.
//!
//! Mirrors [`super::super::ops::vault`]: same returned domain types, same
//! `Result<_, SdkError>` shape on the consumer side. Internal dispatch goes
//! through the wire-services-generated
//! [`VaultServiceClient`](inferadb_ledger_wire_services::VaultServiceClient)
//! instead of the proto-generated tonic client.
//!
//! End-to-end coverage with a real `WireClient` + `WireServer` is deferred
//! to E.7 (TestCluster migration); the unit tests in this file cover the
//! [`RpcError`] → [`SdkError`] conversion and the wire-response → domain-type
//! mapping in isolation. The per-RPC entry points themselves are not
//! exercised yet — [`LedgerClient`](crate::LedgerClient) keeps dispatching
//! through the tonic `ops::vault` path until F.1 flips the connection pool.

use std::sync::Arc;

use bytes::Bytes;
use inferadb_ledger_wire::services::{shared as ws, vault as w};
use inferadb_ledger_wire_services::VaultServiceClient;
use inferadb_ledger_wire_transport::WireClient;

use crate::{
    error::{Result, SdkError},
    ops_wire::rpc_error_to_sdk_error,
    types::admin::{VaultInfo, VaultStatus},
};

/// Issue a `CreateVault` RPC via the wire transport.
///
/// Mirrors [`LedgerClient::create_vault`](crate::LedgerClient::create_vault)
/// at the dispatch layer. The vault slug is generated by the caller (one
/// slug per logical call, reused across retries) so the server-side
/// per-org idempotency keys on slug — a duplicate body is impossible
/// even if the response is lost in flight.
///
/// `request_id` is the 128-bit frame-header correlation ID; the SDK's
/// retry loop is responsible for rotating it across attempts.
///
/// # Errors
///
/// Returns [`SdkError::Connection`] for transport / protocol failures and
/// the appropriate [`SdkError`] variant for server-returned [`WireError`]s
/// (rate-limit family, migration codes, all others land in `Rpc`).
pub(crate) async fn create_vault(
    wire_client: Arc<WireClient>,
    request_id: u128,
    caller: ws::UserSlug,
    organization: ws::OrganizationSlug,
) -> Result<VaultInfo> {
    let vault_slug = inferadb_ledger_types::snowflake::generate_vault_slug()
        .map_err(|e| SdkError::Config { message: format!("generate vault slug: {e}") })?;

    let client = VaultServiceClient::new(wire_client);
    let request = w::CreateVaultRequest {
        organization: Some(organization),
        replication_factor: 0,  // Use server default.
        initial_nodes: vec![],  // Auto-assigned.
        retention_policy: None, // Default: FULL.
        caller: Some(caller),
        slug: Some(vault_slug),
    };
    let response =
        client.create_vault(request, request_id).await.map_err(rpc_error_to_sdk_error)?;
    Ok(domain_vault_info_from_wire_create(response, organization))
}

/// Issue a `GetVault` RPC via the wire transport.
///
/// Mirrors [`LedgerClient::get_vault`](crate::LedgerClient::get_vault) at
/// the dispatch layer. Returns the full [`VaultInfo`] populated from the
/// `GetVaultResponse` (status, nodes, leader, height, state root).
///
/// # Errors
///
/// Same shape as [`create_vault`] — transport failures become
/// [`SdkError::Connection`]; server-returned [`WireError`]s flow through
/// [`from_wire_error_with_correlation`].
pub(crate) async fn get_vault(
    wire_client: Arc<WireClient>,
    request_id: u128,
    caller: ws::UserSlug,
    organization: ws::OrganizationSlug,
    vault: ws::VaultSlug,
) -> Result<VaultInfo> {
    let client = VaultServiceClient::new(wire_client);
    let request = w::GetVaultRequest {
        organization: Some(organization),
        vault: Some(vault),
        caller: Some(caller),
    };
    let response = client.get_vault(request, request_id).await.map_err(rpc_error_to_sdk_error)?;
    Ok(domain_vault_info_from_wire_get(response))
}

/// Issue a `ListVaults` RPC via the wire transport.
///
/// Mirrors [`LedgerClient::list_vaults`](crate::LedgerClient::list_vaults).
/// Returns a tuple `(vaults, next_page_token)` where `next_page_token` is
/// `None` when there are no more pages. The SDK exposes the page token as
/// `Vec<u8>` even though the wire type uses `Bytes` — the boundary
/// conversion happens here so callers stay decoupled from the wire crate.
///
/// # Errors
///
/// Same shape as [`create_vault`].
pub(crate) async fn list_vaults(
    wire_client: Arc<WireClient>,
    request_id: u128,
    caller: ws::UserSlug,
    page_size: u32,
    page_token: Option<Vec<u8>>,
    organization: Option<ws::OrganizationSlug>,
) -> Result<(Vec<VaultInfo>, Option<Vec<u8>>)> {
    let client = VaultServiceClient::new(wire_client);
    let request = w::ListVaultsRequest {
        page_token: page_token.map(Bytes::from),
        page_size,
        organization,
        caller: Some(caller),
    };
    let response = client.list_vaults(request, request_id).await.map_err(rpc_error_to_sdk_error)?;
    let vaults = response.vaults.into_iter().map(domain_vault_info_from_wire_get).collect();
    let next_page_token = response.next_page_token.map(|b| b.to_vec());
    Ok((vaults, next_page_token))
}

/// Issue a `DeleteVault` RPC via the wire transport.
///
/// Mirrors [`LedgerClient::delete_vault`](crate::LedgerClient::delete_vault).
/// The wire response carries a `deleted_at` timestamp that the SDK
/// currently discards — the public API returns `Result<()>`.
///
/// # Errors
///
/// Same shape as [`create_vault`].
pub(crate) async fn delete_vault(
    wire_client: Arc<WireClient>,
    request_id: u128,
    caller: ws::UserSlug,
    organization: ws::OrganizationSlug,
    vault: ws::VaultSlug,
) -> Result<()> {
    let client = VaultServiceClient::new(wire_client);
    let request = w::DeleteVaultRequest {
        organization: Some(organization),
        vault: Some(vault),
        caller: Some(caller),
    };
    client.delete_vault(request, request_id).await.map_err(rpc_error_to_sdk_error)?;
    Ok(())
}

/// Issue an `UpdateVault` RPC via the wire transport.
///
/// Mirrors [`LedgerClient::update_vault`](crate::LedgerClient::update_vault).
/// `retention_policy` accepts the wire-side
/// [`BlockRetentionPolicy`](ws::BlockRetentionPolicy) directly so the wire
/// op surface is fully decoupled from the proto crate. Callers above this
/// layer translate from any domain or proto representation.
///
/// # Errors
///
/// Same shape as [`create_vault`].
pub(crate) async fn update_vault(
    wire_client: Arc<WireClient>,
    request_id: u128,
    caller: ws::UserSlug,
    organization: ws::OrganizationSlug,
    vault: ws::VaultSlug,
    retention_policy: Option<ws::BlockRetentionPolicy>,
) -> Result<()> {
    let client = VaultServiceClient::new(wire_client);
    let request = w::UpdateVaultRequest {
        organization: Some(organization),
        vault: Some(vault),
        retention_policy,
        caller: Some(caller),
    };
    client.update_vault(request, request_id).await.map_err(rpc_error_to_sdk_error)?;
    Ok(())
}

/// Maps a wire `GetVaultResponse` to the domain [`VaultInfo`].
///
/// Pulls the inner slug from each `Option<*Slug>`, defaulting to `0` when
/// absent (mirrors the proto-side `unwrap_or_default()` pattern in
/// [`VaultInfo::from_proto`]). The state root collapses to an empty `Vec`
/// when the wire response omits the hash entirely.
fn domain_vault_info_from_wire_get(resp: w::GetVaultResponse) -> VaultInfo {
    VaultInfo {
        organization: ws::OrganizationSlug::new(resp.organization.map_or(0, |o| o.value())),
        vault: ws::VaultSlug::new(resp.vault.map_or(0, |v| v.value())),
        height: resp.height,
        state_root: resp.state_root.map(|h| h.value.to_vec()).unwrap_or_default(),
        nodes: resp.nodes.into_iter().map(|n| n.value().to_owned()).collect(),
        leader: resp.leader.map(|n| n.value().to_owned()),
        status: wire_vault_status_to_domain(resp.status),
    }
}

/// Maps a wire `CreateVaultResponse` to a partially-populated domain
/// [`VaultInfo`].
///
/// `CreateVaultResponse` is intentionally narrow — it carries the genesis
/// block header but neither the node set nor the current leader (those
/// are implied by the create request itself). The domain shape requires
/// both fields, so this helper fills them with empty-collection defaults
/// and seeds `status` to `Active`. The `organization` slug comes from
/// the caller's request — the wire response doesn't echo it, since the
/// caller already knows which org it targeted.
fn domain_vault_info_from_wire_create(
    resp: w::CreateVaultResponse,
    organization: ws::OrganizationSlug,
) -> VaultInfo {
    let genesis = resp.genesis.unwrap_or_else(empty_block_header);
    VaultInfo {
        organization,
        vault: ws::VaultSlug::new(resp.vault.map_or(0, |v| v.value())),
        height: genesis.height,
        state_root: genesis.state_root.map(|h| h.value.to_vec()).unwrap_or_default(),
        nodes: vec![],
        leader: None,
        status: VaultStatus::Active,
    }
}

/// All-zero placeholder used when the wire response omits the genesis
/// header — keeps `domain_vault_info_from_wire_create` straight-line and
/// avoids an `unwrap_or_default()` impl for the wire `BlockHeader`.
fn empty_block_header() -> ws::BlockHeader {
    ws::BlockHeader {
        height: 0,
        organization: None,
        vault: None,
        previous_hash: None,
        tx_merkle_root: None,
        state_root: None,
        timestamp: 0,
        leader_id: None,
        term: 0,
        committed_index: 0,
        block_hash: None,
    }
}

/// Numeric-tag mapping from the wire `VaultStatus` to the domain enum.
///
/// Mirrors the proto-side `VaultStatus::from_proto(i32)` in
/// [`crate::types::admin`]. An unknown tag collapses to `Unspecified`
/// rather than panicking — same fail-soft contract as the health enum
/// shim.
fn wire_vault_status_to_domain(status: ws::VaultStatus) -> VaultStatus {
    match status {
        ws::VaultStatus::Active => VaultStatus::Active,
        ws::VaultStatus::ReadOnly => VaultStatus::ReadOnly,
        ws::VaultStatus::Deleted => VaultStatus::Deleted,
        ws::VaultStatus::Unspecified => VaultStatus::Unspecified,
    }
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used, clippy::panic, clippy::disallowed_methods)]
mod tests {
    //! Unit coverage for wire-response → domain-type mapping. End-to-end
    //! tests against a real `WireClient` / `WireServer` are deferred to
    //! E.7 (TestCluster migration) — at that point the per-RPC entry
    //! points get exercised in full.

    use bytes::Bytes;

    use super::*;

    fn hash(byte: u8) -> ws::Hash {
        ws::Hash { value: Bytes::copy_from_slice(&[byte; 32]) }
    }

    #[test]
    fn domain_get_response_round_trip() {
        // Build a wire GetVaultResponse with every domain-relevant field
        // populated, project through the helper, assert field-by-field.
        let resp = w::GetVaultResponse {
            organization: Some(ws::OrganizationSlug::new(7)),
            vault: Some(ws::VaultSlug::new(42)),
            height: 100,
            state_root: Some(hash(0xAB)),
            nodes: vec![ws::NodeId::new("node-a"), ws::NodeId::new("node-b")],
            leader: Some(ws::NodeId::new("node-a")),
            status: ws::VaultStatus::ReadOnly,
            retention_policy: None,
        };
        let info = domain_vault_info_from_wire_get(resp);
        assert_eq!(info.organization, ws::OrganizationSlug::new(7));
        assert_eq!(info.vault, ws::VaultSlug::new(42));
        assert_eq!(info.height, 100);
        assert_eq!(info.state_root, vec![0xAB; 32]);
        assert_eq!(info.nodes, vec!["node-a".to_owned(), "node-b".to_owned()]);
        assert_eq!(info.leader.as_deref(), Some("node-a"));
        assert_eq!(info.status, VaultStatus::ReadOnly);
    }

    #[test]
    fn domain_get_response_missing_optionals_default_safely() {
        // Mirror the proto-side `from_proto`'s tolerant shape — a wire
        // response with all optionals missing must not panic; it must
        // produce zero / empty / Unspecified defaults.
        let resp = w::GetVaultResponse {
            organization: None,
            vault: None,
            height: 0,
            state_root: None,
            nodes: vec![],
            leader: None,
            status: ws::VaultStatus::Unspecified,
            retention_policy: None,
        };
        let info = domain_vault_info_from_wire_get(resp);
        assert_eq!(info.organization, ws::OrganizationSlug::new(0));
        assert_eq!(info.vault, ws::VaultSlug::new(0));
        assert_eq!(info.height, 0);
        assert!(info.state_root.is_empty());
        assert!(info.nodes.is_empty());
        assert!(info.leader.is_none());
        assert_eq!(info.status, VaultStatus::Unspecified);
    }

    #[test]
    fn domain_create_response_uses_caller_organization() {
        // Create response doesn't echo the organization back; the helper
        // must wire the caller-provided slug into the resulting VaultInfo.
        let genesis = ws::BlockHeader {
            height: 0,
            organization: None,
            vault: Some(ws::VaultSlug::new(99)),
            previous_hash: None,
            tx_merkle_root: None,
            state_root: Some(hash(0xCD)),
            timestamp: 1_700_000_000_000_000_000,
            leader_id: Some(ws::NodeId::new("leader")),
            term: 1,
            committed_index: 0,
            block_hash: Some(hash(0xEF)),
        };
        let resp =
            w::CreateVaultResponse { vault: Some(ws::VaultSlug::new(99)), genesis: Some(genesis) };
        let info = domain_vault_info_from_wire_create(resp, ws::OrganizationSlug::new(11));
        assert_eq!(info.organization, ws::OrganizationSlug::new(11));
        assert_eq!(info.vault, ws::VaultSlug::new(99));
        assert_eq!(info.height, 0);
        assert_eq!(info.state_root, vec![0xCD; 32]);
        // Create response carries no node set / leader info — domain
        // defaults to empty + None + Active.
        assert!(info.nodes.is_empty());
        assert!(info.leader.is_none());
        assert_eq!(info.status, VaultStatus::Active);
    }

    #[test]
    fn domain_create_response_missing_genesis_defaults_safely() {
        // Server may legitimately omit the genesis block on a create
        // response (e.g. provisional-state replies during cluster
        // bootstrap). The helper must not panic; height + state_root
        // must collapse to zero / empty.
        let resp = w::CreateVaultResponse { vault: Some(ws::VaultSlug::new(5)), genesis: None };
        let info = domain_vault_info_from_wire_create(resp, ws::OrganizationSlug::new(1));
        assert_eq!(info.vault, ws::VaultSlug::new(5));
        assert_eq!(info.height, 0);
        assert!(info.state_root.is_empty());
    }

    #[test]
    fn wire_vault_status_each_variant_maps_correctly() {
        // Pin the per-variant mapping so a future addition to the wire
        // enum doesn't silently fall through to Unspecified without a
        // matching domain variant.
        assert_eq!(
            wire_vault_status_to_domain(ws::VaultStatus::Unspecified),
            VaultStatus::Unspecified
        );
        assert_eq!(wire_vault_status_to_domain(ws::VaultStatus::Active), VaultStatus::Active);
        assert_eq!(wire_vault_status_to_domain(ws::VaultStatus::ReadOnly), VaultStatus::ReadOnly);
        assert_eq!(wire_vault_status_to_domain(ws::VaultStatus::Deleted), VaultStatus::Deleted);
    }

    #[test]
    fn block_retention_mode_oneof_round_trips_via_postcard() {
        // BlockRetentionMode is a #[repr(i32)] tagged enum; the wire
        // crate's BlockRetentionPolicy wraps it in `Option<...>`. Verify
        // each variant survives a postcard round-trip without tag
        // collision — the same encoding the wire transport uses.
        for mode in [
            ws::BlockRetentionMode::Unspecified,
            ws::BlockRetentionMode::Full,
            ws::BlockRetentionMode::Compacted,
        ] {
            let policy =
                ws::BlockRetentionPolicy { mode: Some(mode), retention_blocks: Some(1234) };
            let bytes = postcard::to_allocvec(&policy).unwrap();
            let decoded: ws::BlockRetentionPolicy = postcard::from_bytes(&bytes).unwrap();
            assert_eq!(policy, decoded);
        }
    }

    #[test]
    fn block_retention_mode_repr_values_match_proto() {
        // Lock in the integer tags so a cross-protocol audit (proto vs
        // wire) can grep for the same values. The wire enum is
        // #[repr(i32)] = 0/1/2 by design.
        assert_eq!(ws::BlockRetentionMode::Unspecified as i32, 0);
        assert_eq!(ws::BlockRetentionMode::Full as i32, 1);
        assert_eq!(ws::BlockRetentionMode::Compacted as i32, 2);
    }

    #[test]
    fn vault_status_repr_values_match_proto() {
        // Mirror the proto-side `VaultStatus` discriminant values exactly
        // so the wire encoding is byte-compatible with the proto encoding
        // — the migration relies on the same i32 tags surviving the
        // protocol swap.
        assert_eq!(ws::VaultStatus::Unspecified as i32, 0);
        assert_eq!(ws::VaultStatus::Active as i32, 1);
        assert_eq!(ws::VaultStatus::ReadOnly as i32, 2);
        assert_eq!(ws::VaultStatus::Deleted as i32, 3);
    }

    #[test]
    fn empty_block_header_is_all_default() {
        // The placeholder used when CreateVaultResponse.genesis is None
        // must produce all-zero / None fields — anything else would
        // surface as bogus data in domain output.
        let h = empty_block_header();
        assert_eq!(h.height, 0);
        assert!(h.organization.is_none());
        assert!(h.vault.is_none());
        assert!(h.previous_hash.is_none());
        assert!(h.tx_merkle_root.is_none());
        assert!(h.state_root.is_none());
        assert_eq!(h.timestamp, 0);
        assert!(h.leader_id.is_none());
        assert_eq!(h.term, 0);
        assert_eq!(h.committed_index, 0);
        assert!(h.block_hash.is_none());
    }

    #[test]
    fn block_header_hash_round_trips_via_postcard() {
        // BlockHeader carries multiple Option<Hash> fields. Guard against
        // postcard tag collisions where two consecutive Option<Hash>
        // fields could decode in the wrong order.
        let header = ws::BlockHeader {
            height: 7,
            organization: Some(ws::OrganizationSlug::new(1)),
            vault: Some(ws::VaultSlug::new(2)),
            previous_hash: Some(hash(0x11)),
            tx_merkle_root: Some(hash(0x22)),
            state_root: Some(hash(0x33)),
            timestamp: 1_700_000_000,
            leader_id: Some(ws::NodeId::new("leader")),
            term: 3,
            committed_index: 5,
            block_hash: Some(hash(0x44)),
        };
        let bytes = postcard::to_allocvec(&header).unwrap();
        let decoded: ws::BlockHeader = postcard::from_bytes(&bytes).unwrap();
        assert_eq!(header, decoded);
        // Assert the hash bytes survived intact, not just structurally
        // equal — a wrong-length copy would compare equal under PartialEq
        // if both sides were truncated identically.
        assert_eq!(decoded.previous_hash.as_ref().unwrap().value.len(), 32);
        assert_eq!(decoded.state_root.as_ref().unwrap().value.as_ref(), &[0x33; 32]);
    }

    #[test]
    fn list_vaults_page_token_round_trips_through_bytes() {
        // The SDK exposes the page token as Vec<u8>; the wire request
        // type uses Bytes. Verify the boundary conversion preserves
        // byte content in both directions — a regression here would
        // silently break pagination.
        let domain_token: Vec<u8> = vec![0xDE, 0xAD, 0xBE, 0xEF];
        let wire_token = Bytes::from(domain_token.clone());
        assert_eq!(wire_token.as_ref(), domain_token.as_slice());
        let back: Vec<u8> = wire_token.to_vec();
        assert_eq!(back, domain_token);
    }
}
